server:
  port: 8083

logging:
  level:
    org.springframework.web: INFO

spring:
  application:
    name: ariss-barrier
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ariss_barrier
        use_sql_comments: true
        format_sql: true
        criteria:
          literal_handling_mode: BIND
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unit_techno?currentSchema=ariss_barrier
    username: ariss_barrier_admin
    password: squd
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true

  cloud:
    config:
      discovery:
        enable: true
        service-id: ariss_barrier

event:
  type:
    7777:
      info: "административный корпус"
      entryType: OUT
    8888:
      info: "задний проход"
      entryType: IN